AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pegando seu cep o seu endereço... ou o de alguém né

Globals:
  Function:
    Timeout: 3

Resources:

  # YourAddressHttpApi:
  #   Type: AWS::Serverless::HttpApi

  GetAddressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.getAddress
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        GetAddress:
          Type: HttpApi
          Properties:
            # ApiId: !Ref YourAddressHttpApi
            Path: /address
            Method: get
